Use setuptools-scm to generate version from SCM (fallback to static)
pypa/build pull request #172
Opened 2020-10-27 19:52 UTC by gaborbernat

👍 Compared to what we have now we're a bit ahead in sense of post this we'll only have one version number within our repo, and the version number will be automatically generated from the SCM (if present). We'll need to make sure to update the version file before we do a release, but we're already here today.

2020-10-27 20:00 UTC, FFY00 requested changes
I have said I do not want to pull any other bootstraping dependencies.

2020-10-27 20:04 UTC, gaborbernat commented
> I have said I do not want to pull any other bootstraping dependencies.

* ``bootstrapping``

Look man, this is not a hard dependency, it's a soft one. The package works just fine (as is today) without it. But if installed provide additional functionality today not present.

2020-10-27 20:13 UTC, pganssle commented
Yeah, it has an additional dependency in the `pyproject.toml`, but anyone who cares about bootstrapping isn't blindly pulling in the `pyproject.toml` dependencies anyway.

For building from `sdist`, I think `setuptools_scm` isn't even really used, since there's no git for it to even interact with (though there's no way to indicate this in `pyproject.toml` without modifying the file in place as part of the sdist build).

2020-10-28 00:45 UTC, layday commented
I assume the tests are failing because we need a `MANIFEST.in` for `version.fallback` for when the `setuptools_scm` file finder is not in use (i.e. without isolation). `setuptools_scm` will pull everything that's tracked by the SCM into the sdist automatically.  We might also want to customise `MANIFEST.in` to exclude files which wouldn't be included by vanilla `setuptools` if sdist parity is important.

2020-10-28 03:07 UTC, FFY00 approved these changes
It is still annoying for packagers, but sure.

Please properly document that `setuptools-scm` is not actually required for the build, and the project can be bootstrapped without it.

Other than that, do whatever.

2020-10-28 08:31 UTC, gaborbernat commented
> It is still annoying for packagers, but sure.

Why? Can you expand on this a bit? 😊

2020-10-31 02:53 UTC, FFY00 commented
> Why? Can you expand on this a bit?

Not all packagers will know this, it takes a bit of digging to find out about this.

We should definitely document this.

2020-10-31 02:56 UTC, FFY00 commented on src/build/__init__.py
> +from .version import __version__
Did you forget to commit `version.py`?

2020-10-31 02:57 UTC, FFY00 commented on src/build/__init__.py
> +from .version import __version__
nvm

2020-11-01 15:26 UTC, webknjaz approved these changes

2021-02-13 07:38 UTC, gaborbernat commented
Will create new PR.

2021-02-13 07:38 UTC, closed without merging