Add exports to `__init__.py` for strict type checking support
pypa/build pull request #189
Opened 2020-11-14 11:43 UTC by layday

With `mypy --strict` (or `pyright: strict`, etc.) you cannot
import symbols which are not explicitly (re-)exported.
This can be accomplished in one of two ways: using `__all__`
or with `import x as x` if a symbol is imported from another module.

2020-11-22 15:40 UTC, FFY00 requested changes
Sorry for the late review!

You can add `check_dependency` and `ConfigSettings`.

2020-11-22 15:44 UTC, layday commented
I wasn't sure if `check_dependency` should be public, especially if we're looking to eventually import it or its equivalent from `packaging`. What's your opinion?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Sunday, November 22, 2020 5:40 PM, Filipe Laíns <notifications@github.com> wrote:

> @FFY00 requested changes on this pull request.
>
> Sorry for the late review!
>
> You can add check_dependency and ConfigSettings.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/pypa/build/pull/189#pullrequestreview-536073763), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AHNRFWEC6T2LIY2YEOU5XHTSREWH5ANCNFSM4TVP634A).

2020-11-26 13:20 UTC, FFY00 commented
Well, it is already public. And we will need it for the wheel installer. I'd really like to see this going to someplace else, but that doesn't seem like it's gonna happen anytime soon.

From a bootstraping perspective, I would much rather have it here than in another custom package, as I would need `build` anyway. So, I say we temporarily provide it here. When it gets adopted somewhere else, we can import it from there and add a deprecation warning.

2020-11-26 13:27 UTC, FFY00 approved these changes

2020-11-26 16:20 UTC, merged