env: upgrade pip on all versions of Python under 3.6.6
pypa/build pull request #227
Opened 2021-02-08 18:04 UTC by layday

Fixes #226.

2021-02-08 19:12 UTC, henryiii approved these changes
This looks reasonable to me, at least. :)

2021-02-08 19:18 UTC, gaborbernat requested changes
A better solution would be to instead set PIP_NO_WARN_SCRIP_LOCATION=1 env-var. This would degrade better to versions without the flag and would not need this update dance.

2021-02-08 19:18 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/4c1ce240c202fc218c52955238d0de6f/tenor.gif)

2021-02-08 19:21 UTC, henryiii commented
I think it still should do the update dance, though? As it does need 10+ anyway, correct? This was just a side effect (an avoidable one, as you point out), but it should be using 10+?

2021-02-08 20:56 UTC, layday commented
I don't know what we need 10+ for, was it just `--no-warn-script-location`?

2021-02-08 20:59 UTC, henryiii commented
I was just basing my observation on the comment in the code about 10 being needed - this used to work just fine before, so maybe swapping for the environment variable and dropping the pip upgrade is better?

I've fixed my immediate issue by swapping ubuntu-latest for ubuntu-20.04, but obviously that's just a workaround.

2021-02-08 21:35 UTC, layday commented
Was hoping @gaborbernat might know :)

2021-02-08 21:38 UTC, gaborbernat commented
I guess upgrading pip is safer. For example, old pip might not understand correctly the metadata specification of wheels/sdist, which might cause certain dependencies to fail.

2021-02-08 22:45 UTC, FFY00 requested changes
Can you add an entry to the changelog? You'll need to re-add the `Unreleased` section, which was removed when I tagged the latest release.
https://github.com/pypa/build/commit/a5a0b3860cff68ac9aad896fad22febd2b8d3718

2021-02-08 23:13 UTC, FFY00 commented on CHANGELOG.rst
> +- Fix error from unrecognised pip flag on Python 3.6.0 to 3.6.5 (`PR #227`_, Fixes `#226`_)
You need to add the links as below.

2021-02-08 23:18 UTC, FFY00 approved these changes

2021-02-09 13:18 UTC, merged

2021-02-09 13:56 UTC, henryiii commented
Any chance we might get a release? Dependabot is going through, updating all my repos to PyPI publish 1.4.2, and they are breaking due to the fact that build is broken, for example https://github.com/scikit-hep/uhi/pull/5. I can manually change to using ubuntu-20.04, but it would be nice not to have to change a few dozen repos and add a note to our developer docs. Thanks! :)

2021-02-09 15:08 UTC, FFY00 commented
I will do a bugfix release.

2021-02-09 15:09 UTC, henryiii commented
I really appreciate it, thank you very much. :)