restore compatibility with python3.6 and python3.7
pypa/build pull request #339
Opened 2021-08-04 09:54 UTC by wouterdb

fixes #338

2021-08-04 10:13 UTC, gaborbernat requested changes

2021-08-04 10:13 UTC, gaborbernat commented on src/build/env.py
> +        _logger.log(logging.INFO, message)
Rather than blindly removing it can we keep it for 3.8+?

2021-08-04 10:26 UTC, gaborbernat reviewed
Can you add a test that validates/catches this issue?

2021-08-04 10:37 UTC, wouterdb commented on src/build/env.py
> +            _logger.log(logging.INFO, "%s", message, stacklevel=2)
I spotted a second problem, which I also fixed

2021-08-04 10:46 UTC, layday commented
How are the tests passing for 3.6 and 3.7?

2021-08-04 10:49 UTC, wouterdb commented on src/build/env.py
> +            _logger.log(logging.INFO, "%s", message, stacklevel=2)
(never mind, problem doesn't occur in this setup)

2021-08-04 10:51 UTC, wouterdb commented
> How are the tests passing for 3.6 and 3.7?

if the log level is below INFO, the problem doesn't manifest.

If you would execute the tests with `--log-cli-level=INFO` they would fail

2021-08-04 10:51 UTC, layday commented
Okay, we are not testing the logging directly.  We are only testing the CLI's output and the CLI overloads the log methods.

This should've also been caught by the type checker unless the stubs in the typesheds are wrong.

2021-08-04 11:03 UTC, layday commented
mypy selects the correct overload but does not produce an error when it's called with `stacklevel` because `Logger.log` accepts `**kwargs` (see https://github.com/python/typeshed/blob/b2e429cd41347ce48a96feaa1681726d8f77fbfb/stdlib/logging/__init__.pyi#L218).  This is incorrect.

2021-08-04 16:45 UTC, FFY00 commented on tests/test_env.py
> +    caplog.set_level(logging.INFO)
Instead of doing this, could you add a test in `test_projectbuilder.py` to verify the default `ProjectBuilder.log` implementation is correct?

2021-08-04 17:12 UTC, FFY00 commented on tests/test_env.py
> +    caplog.set_level(logging.INFO)
Sorry, I end up doing it myself as I has the time and I want this fixed ASAP :sweat_smile:

2021-08-04 17:13 UTC, FFY00 commented
@gaborbernat or @layday please take a look.

2021-08-04 17:15 UTC, gaborbernat reviewed
Where should we see the stacklevel=2 impact? 🤔

2021-08-04 17:25 UTC, FFY00 commented
`record.lineno`, it makes the log be registered to the `ProjectBuilder.log` caller, instead of the line where we actually call the log. Right now, I am not sure how to write tests for this without having to fix them every time we touch the code. The best we could do is mocking the call and make sure `stacklevel` is passed, although that is kinda just duplicating the code. I would merge this as-is and if welcome better tests in the future.

2021-08-04 21:54 UTC, gaborbernat reviewed
I'd prefer to have a test that validates the stack level, it's alright that we need to change the test when line numbers change.

2021-08-05 00:00 UTC, FFY00 commented
Sure, but if this becomes an annoyance, we will remove it.

2021-08-05 06:45 UTC, gaborbernat approved these changes

2021-08-05 06:45 UTC, merged

2021-08-05 14:20 UTC, henryiii commented
> mypy selects the correct overload but does not produce an error when it's called with `stacklevel` because `Logger.log` accepts `**kwargs` (see https://github.com/python/typeshed/blob/b2e429cd41347ce48a96feaa1681726d8f77fbfb/stdlib/logging/__init__.pyi#L218). This is incorrect.

Interesting, you pass keyword arguments via dict to *args, so yes, this is true - it's only used to pass things through to `self._log`, which does not accept arbitrary keyword arguments. I can make a PR to type shed unless you plan to do it, @layday. Honestly, this sort of shortcut seems like it should also be made explicit in the stdlib, too.

2021-08-05 14:22 UTC, layday commented
> I can make a PR to type shed unless you plan to do it, @layday.

I'd appreciate it if you could, might not get around to it for a few days.